language: c++
dist: trusty

python: '3.6'

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - ENABLE_GTK3=false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - kubuntu-backports
          packages:
            - gcc-8
            - g++-8
            - libpng-dev
            - libsdl2-net-dev
        artifacts:
          region: eu-central-1
          working_dir: build
          paths:
            - imdoom64
            - imdoom64.pk3

before_install:
  - eval "${MATRIX_EVAL}"

  # Set python version
  - pyenv global 3.6

  # Install mesonbuild
  - pip3 install meson

  # Install ninja
  - mkdir -p $HOME/bin
  - cd $HOME/bin
  - export PATH=$HOME/bin:$PATH
  - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - unzip ninja-linux.zip
  - rm ninja-linux.zip
  - cd -

  # Print settings
  - which $CC
  - which $CXX
  - $CC --version
  - $CXX --version
  - meson --version
  - ninja --version

script:
  # Compile our thing!
  - mkdir build && cd build
  - meson --default-library=static --buildtype=release -Denable_gtk3=${ENABLE_GTK3} ..
  - ninja
