language: c++
dist: trusty

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - CC=gcc-8
        - CXX=g++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - kubuntu-backports
          packages:
            - gcc-8
            - g++-8
            - python3.5
            - python3-pip
            - ninja-build
            - libpng-dev
            - libsdl2-net-dev

before_install:
  # Set python3.5 as default
  - alias python=python3.5
  - python --version

  # Install mesonbuild
  - pip3 install meson

  # Install ninja
  - cd $HOME/.local/bin
  - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - unzip ninja-linux.zip
  - rm ninja-linux.zip
  - cd -

  # Print settings
  - which $CC
  - which $CXX
  - $CC --version
  - $CXX --version
  - meson --version
  - ninja --version


script:
  # Compile our thing!
  - mkdir build && cd build
  - meson --default-library=static --buildtype=release ..
  - ninja
